### ISSUE TITLE
Lawyer Black Suitskirt not working, or Formal Tab not working.

### ISSUE THREAD

**Issue by Some2s** [SeeBeeSee/Monkestation2.0-Breadbox#1]
A few months ago I bought the lawyer black suitskirt item from the loadout store, it took my 5K Monkecoin, and then it appeared in the formal tab like normal. but when the next round rolled over it disappeared from my inventory, and wanted me to buy it again without giving me back my 5K in Monkecoin. I thought it might have been a one off thing, so a month or so later I tried it again. Went into the store, bought the suitskirt again stayed for the round I bought it, left once the next round rolled over again. I've lost 10K from this and I don't know if the formal tab itself is broken because it doesn't have any patron items in it, or its just the one item, but I'm too afraid of losing more money to find out.
![Screenshot 2024-07-03 141150](https://github.com/SeeBeeSee/Monkestation2.0-Breadbox/assets/160663664/edb04999-b5c8-4caa-9eeb-cad5df4cb81d)

**Comment by Some2s** [comment]
posted this in the wrong github, fuck.

**Comment by SeeBeeSee** [comment]
> posted this in the wrong github, fuck.

Spooked the hell out of me, that did. lmao
